version: "3.5"

services:
  web:
    image: webdevops/php-nginx-dev:7.4
    working_dir: /app
    depends_on:
      - database
    volumes:
      - .:/app
    environment:
      PHP_DATE_TIMEZONE: "Europe/Paris"
      WEB_DOCUMENT_ROOT: /app/public
      WEB_DOCUMENT_INDEX: index.php

  database:
    image: mysql:8.0
    command: mysqld --default-authentication-plugin=mysql_native_password
    volumes:
      - 'db_data:/var/lib/mysql'

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    depends_on:
      - database
    environment:
      PMA_HOST: database

volumes:
  db_data:
    driver: local
